apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: simulator
  labels:
    app: simulator
spec:
  selector:
    matchLabels:
      app: simulator
  endpoints:
    - port: metrics
      path: /metrics
      interval: 15s
