apiVersion: external-secrets.io/v1beta1
kind: ClusterSecretStore
metadata:
  name: aws-parameter-store
spec:
  provider:
    aws:
      service: ParameterStore
      region: ap-southeast-1
      auth:
        jwt:
          serviceAccountRef:
            name: external-secrets
            namespace: external-secrets
---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: platform-secrets
spec:
  refreshInterval: "1h"
  secretStoreRef:
    name: tf1-aws-parameter-store
    kind: ClusterSecretStore
  target:
    name: platform-secrets-synced
    creationPolicy: Owner
  data:
  - secretKey: JIRA_EMAIL
    remoteRef:
      key: /xbrain-cdo5/sandbox/jira_email
  - secretKey: JIRA_URL
    remoteRef:
      key: /xbrain-cdo5/sandbox/jira_url
  - secretKey: JIRA_USER
    remoteRef:
      key: /xbrain-cdo5/sandbox/jira_user
  - secretKey: JIRA_PROJECT_KEY
    remoteRef:
      key: /xbrain-cdo5/sandbox/jira_project_key
  - secretKey: JIRA_TOKEN
    remoteRef:
      key: /xbrain-cdo5/sandbox/jira_api_key
  - secretKey: SLACK_WEBHOOK_URL
    remoteRef:
      key: /xbrain-cdo5/sandbox/slack_webhook_url
  - secretKey: SQS_QUEUE_URL
    remoteRef:
      key: /xbrain-cdo5/sandbox/sqs_queue_url
